name: Cleanup Preview Deployments
on:
  pull_request:
    types: [labeled]

env:
  VERCEL_TEAM: ${{ secrets.VERCEL_TEAM }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  PR_NUMBER: ${{ github.event.number }}

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: get-aliases
        name: Get a list of all Vercel aliases
        run: echo "aliases=$(vercel alias ls --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_TEAM }})" >> $GITHUB_ENV
